config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update profile]

    resources :franchises

    namespace :admin do
      resources :users, only: %i[index create]
    end
    root 'pages#index'
    get '/pricing' => 'pages#pricing'
    get '/add' => 'pages#add'
    get '/about' => 'pages#about'
    get '/business_magazine' => 'pages#business_magazine'

  end  
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %> 
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>  
      <% end %>
    </ul>  
  <% end %>

app/views/shared/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">



<!--footer starts from here-->
<footer class="footer mt-4" >
<div class="container bottom_border  ">
<div class="row">
<div class=" col-sm-4 col-md col-sm-4  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Find us</h5>
<!--headin5_amrc-->
<p class="mb10">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
<p><i class="fa fa-location-arrow"></i> 9878/25 sec 9 rohini 35 </p>
<p><i class="fa fa-phone"></i>  +91-9999878398  </p>
<p><i class="fa fa fa-envelope"></i> info@example.com  </p>


</div>


<div class=" col-sm-4 col-md  col-6 col">
<h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>
<!--headin5_amrc-->
<ul class="footer_ul_amrc">
<li><a href="http://webenlance.com">Image Rectoucing</a></li>
<li><a href="http://webenlance.com">Clipping Path</a></li>
<li><a href="http://webenlance.com">Hollow Man Montage</a></li>
<li><a href="http://webenlance.com">Ebay & Amazon</a></li>
<li><a href="http://webenlance.com">Hair Masking/Clipping</a></li>
<li><a href="http://webenlance.com">Image Cropping</a></li>
</ul>
<!--footer_ul_amrc ends here-->
</div>


<div class=" col-sm-4 col-md  col-6 col">
<h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>
<!--headin5_amrc-->
<ul class="footer_ul_amrc">
<li><a href="http://webenlance.com">Remove Background</a></li>
<li><a href="http://webenlance.com">Shadows & Mirror Reflection</a></li>
<li><a href="http://webenlance.com">Logo Design</a></li>
<li><a href="http://webenlance.com">Vectorization</a></li>
<li><a href="http://webenlance.com">Hair Masking/Clipping</a></li>
<li><a href="http://webenlance.com">Image Cropping</a></li>
</ul>
<!--footer_ul_amrc ends here-->
</div>


<div class=" col-sm-4 col-md  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Follow us</h5>
<!--headin5_amrc ends here-->

<ul class="footer_ul2_amrc">
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a></p></li>
</ul>
<!--footer_ul2_amrc ends here-->
</div>
</div>
</div>


<div class="container">
<ul class="foote_bottom_ul_amrc">
<li><%= nav_tab t('menu.home'), root_path %></li>
<li><%= nav_tab 'About Us', about_path %></li>
<li><a href= "#">Services</a></li>
<li><%= nav_tab 'Pricing', pricing_path %></li>
<li><%= nav_tab 'Business magazine', business_magazine_path %></li>
<li><%= nav_tab 'About Us', about_path %></li>
</ul>
<!--foote_bottom_ul_amrc ends here-->
<p class="text-center">Copyright @2021 | Designed With by <a href="#">Invebos.com</a></p>

<ul class="social_footer_ul">
<li><a href="http://webenlance.com"><i class="fab fa-facebook-f"></i></a></li>
<li><a href="http://webenlance.com"><i class="fab fa-twitter"></i></a></li>
<li><a href="http://webenlance.com"><i class="fab fa-linkedin"></i></a></li>
<li><a href="http://webenlance.com"><i class="fab fa-instagram"></i></a></li>
</ul>
<!--social_footer_ul ends here-->
</div>

</footer>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab t('menu.home'), root_path,
            class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Franchises', franchises_path,
            class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Pricing', pricing_path,
            class: 'nav-link px-2', current_page: current_page %></li> 
          <% if user_signed_in? %>  
            <li><%= nav_tab 'Add', add_path,
              class: 'nav-link px-2', current_page: current_page %></li> 
            <li><%= nav_tab 'Business magazine', business_magazine_path,
              class: 'nav-link px-2', current_page: current_page %></li>
            <li><%= nav_tab 'About Us', about_path,
              class: 'nav-link px-2', current_page: current_page %></li>   
            <li><%= nav_tab 'Admin', admin_users_path,
              class: 'nav-link px-2', current_page: current_page %></li>   
          <% end %> 
        </ul>
         

       
    <!----------------------------------------------------------->
         
<!----------------------------------------------------------->




        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-white',
              data: {"bs-toggle": 'dropdown'} do %>
              <%= tag.div '', class: "flag #{I18n.locale}-flag mt-1" %>
              <%= t I18n.locale %>
            <% end %>


            
            <ul class="dropdown-menu ">
              <% I18n.available_locales.each do |locale| %>
                <li>
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), root_path(locale: locale),
                      class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul> 


        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-white',
                data: {"bs-toggle": 'dropdown'} do %>
                <%= current_user.gravatar %>
                <%= current_user.name_or_email %>
              <% end %>          
                
                
              <ul class="dropdown-menu ">
              

               <li><hr class="dropdown-divider"></li>

                <li>

                  <%= link_to 'Profile', edit_user_path(current_user),
                    class: 'dropdown-item' %>
                </li>
               
               <li><hr class="dropdown-divider"></li>

               
             

               

                

                <li>
                  <%= link_to 'Log Out', session_path,
                    class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab 'Sign Up', new_user_path,
              class: 'nav-link px-2', current_page: current_page %></li>

            <li><%= nav_tab 'Log In', new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>